# Generated by Django 3.0.7 on 2020-06-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_auto_20200622_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='is_free',
        ),
    ]
