# Generated by Django 3.0.7 on 2020-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0003_remove_cabinet_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_of_week',
            field=models.CharField(choices=[('ПН', 0), ('ВТ', 1), ('СР', 2), ('ЧТ', 3), ('ПТ', 4), ('СБ', 5), ('ВС', 6)], max_length=10),
        ),
    ]
